events {
}

http {
    include /etc/nginx/mime.types;

    # Optimisation SSL (reduces CPU loads)
    ssl_session_cache shared:SSL:10m; # Allocates 10Mo of RAM for cache
    ssl_session_timeout 10m; # 10 minutes before doing handshake again

    server {
        listen 443 ssl; # IPv4 with SSL/TLS (https)
        listen [::]:443 ssl; # IPv6

        server_name gwen.42.fr;

        # Generate SSL/TLS certificate and key
        ssl_certificate /etc/nginx/ssl/gwen.crt;
        ssl_certificate_key /etc/nginx/ssl/gwen.key;
        ssl_protocols TLSv1.2 TLSv1.3;

        # It's where all the files (HTML pages, PHP files...) of the website are
        root /var/www/html;

        # If user don't specify a name, return these by default
        index index.php index.html index.htm;

        location / {
            # Try to find the file, if not, redirect to 
            try_files $uri $uri/ /index.php$is_args$args;
        }

        # Transfer PHP files to PHP-FPM
        # (FastCGI/translating PHP files because NGINX don't understand it)
        location ~ \.php$ {
            fastcgi_split_path_info ^(.+\.php)(/.+)$;
            fastcgi_pass wordpress:9000;
            fastcgi_index index.php;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param PATH_INFO $fastcgi_path_info;
        }

        location /static/ {
            alias /var/www/static_page/;
            index index.html;
            try_files $uri $uri/ /index.html;
        }

        location /adminer/ {
            proxy_pass http://adminer:8080/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https;
        }

        location /cadvisor/ {
            proxy_pass http://cadvisor:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https;
            proxy_redirect off;
        }
    }
}