services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - 443:443
    volumes:
      - wordpress:/var/www/html:ro
      - ./requirements/bonus/static_page/tools:/var/www/static_page:ro
    restart: always
    depends_on:
      - wordpress
    networks:
      - oiia-network
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    depends_on:
      - mariadb
    restart: always
    networks:
      - oiia-network
    volumes:
      - wordpress:/var/www/html
    env_file:
      - .env
    secrets:
      - wp_admin_password
      - wp_admin_user
      - mariadb_user_password

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - mariadb:/var/lib/mysql
    restart: always
    networks:
      - oiia-network
    env_file:
      - .env
    secrets:
      - mariadb_root_password
      - mariadb_user_password
  redis:
    container_name: redis
    build: ./requirements/bonus/redis
    depends_on:
      - wordpress
    restart: always
    ports:
      - 6379:6379
    volumes:
      - wordpress:/var/www/html
    networks:
      - oiia-network
  vsftpd:
    container_name: vsftpd
    build: ./requirements/bonus/ftp
    depends_on:
      - wordpress
    ports:
      - "21:21"
      - "21100-21110:21100-21110"
    volumes:
      - wordpress:/var/www/html
    env_file:
      - .env
    restart: always
    networks:
      - oiia-network
    secrets:
      - ftp_password
  static_page:
    container_name: static_page
    build: ./requirements/bonus/static_page
    restart: always
    networks:
      - oiia-network
  adminer:
    container_name: adminer
    build: ./requirements/bonus/adminer
    restart: always
    depends_on:
      - mariadb
    networks:
      - oiia-network
  cadvisor:
    container_name: cadvisor
    build: ./requirements/bonus/cadvisor
    restart: always
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - 8080:8080
    networks:
      - oiia-network

# Declarations
volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: /home/gwen/data/wordpress
      o: bind
  mariadb:
    driver: local
    driver_opts:
      type: none
      device: /home/gwen/data/mariadb
      o: bind

# By default, the network's driver is "bridge"
# Other drivers are: "host", "none", "overlay", "ipvlan" and "macvlan"
networks:
  oiia-network:
    driver: bridge

secrets:
  mariadb_root_password:
    file: ../.secrets/db_root_password.txt
  mariadb_user_password:
    file: ../.secrets/db_password.txt
  ftp_password:
    file: ../.secrets/ftp_password.txt
  wp_admin_password:
    file: ../.secrets/wp_admin_password.txt
  wp_admin_user:
    file: ../.secrets/wp_admin_user.txt