services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - 443:443
    volumes:
      - wordpress:/var/www/html:ro
      - ./requirements/bonus/static_page/tools:/var/www/static_page:ro
    restart: always
    depends_on:
      - wordpress
    networks:
      - oiia-network
    env_file:
      - .env
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    depends_on:
      - mariadb
    restart: always
    env_file:
      - .env
    networks:
      - oiia-network
    volumes:
      - wordpress:/var/www/html
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    env_file:
      - .env
    volumes:
      - mariadb:/var/lib/mysql
    restart: always
    networks:
      - oiia-network
  redis:
    container_name: redis
    build: ./requirements/bonus/redis
    depends_on:
      - wordpress
    restart: always
    ports:
      - 6379:6379
    volumes:
      - wordpress:/var/www/html
    networks:
      - oiia-network
  vsftpd:
    container_name: vsftpd
    build: ./requirements/bonus/ftp
    depends_on:
      - wordpress
    ports:
      - "21:21"
      - "21100-21110:21100-21110"
    volumes:
      - wordpress:/var/www/html
    environment:
      FTP_USER: ${FTP_USER}
      FTP_PASS: ${FTP_PASS}
    restart: always
    networks:
      - oiia-network
  static_page:
    container_name: static_page
    build: ./requirements/bonus/static_page
    restart: always
    ports:
      - "8080:8080"
    networks:
      - oiia-network

# Declarations
volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: /home/gwen/data/wordpress
      o: bind
  mariadb:
    driver: local
    driver_opts:
      type: none
      device: /home/gwen/data/mariadb
      o: bind

# By default, the network's driver is "bridge"
# Other drivers are: "host", "none", "overlay", "ipvlan" and "macvlan"
networks:
  oiia-network:
    driver: bridge